version: '3.3'
services:
  mysql:
    container_name: "mysql-gin"
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=mysql
